spring:
  profiles:
    group:
      local: local,common

---

spring:
  profiles:
    group:
      prod: prod,common

---

spring:
  profiles:
    group:
      test: prod,common
---

spring:
  config:
    activate:
      on-profile: "common"
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    check-template-location: true
    suffix: .html

server:
  port: 9091

default:
  profile:
    image: "default-profile.png"

---

spring:
  config:
    activate:
      on-profile: "local"
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mygram?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: 1234

logging:
  level:
    org.springframework.web: trace

upload:
  path: "C:/Users/kms/IdeaProjects/mygram/upload/"

---

spring:
  config:
    activate:
      on-profile: "prod"
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mygramdb.c2ejxfeifgj5.ap-northeast-2.rds.amazonaws.com:3306/mygram?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: ${FACE_BOOK_CLIENT_ID}
            client-secret: ${e37b18be77909921f6e47041876cbd42}
            scope:
              - public_profile
              - email

logging:
  level:
    org.springframework.web: trace

upload:
  path: "upload/"
