server:
  port: 9091

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    check-template-location: true
    suffix: .html

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      enabled: true

  datasource:
    dirverClassName: com.mysql.cj.jdbc.Dirver
    url: jdbc:mysql://localhost:3306/mygram?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password:

logging:
  level:
    org.springframework.web: trace

upload:
  path: "C:/Users/kms/IdeaProjects/mygram/upload/"

default:
  profile:
    image: "default-profile.png"